### ISSUE TITLE
Write a bootstrap.nix

### ISSUE THREAD

**Issue by tmplt** [tmplt/nixos-config#10]
To deploy a system with nixops the system first needs to have a running SSH server. A simple `boostrap.nix` could configure this where (after the system is built with this) then use nixops as usual.

**Comment by Tmplt** [comment]
This is only an issue for hands-on systems.

**Comment by Tmplt** [comment]
Alternatively, a NixOS ISO-file could be generated with a SSH server for appropriate keys (`ssh-keys.nix`).

**Comment by Tmplt** [comment]
For VPS, we can likely use https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/openstack/openstack-image.nix, where we include `common-server.nix`.
